// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: TestStatus.proto
// Protobuf Java Version: 4.29.3

public final class TestStatusOuterClass {
  private TestStatusOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TestStatusOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool motorSpinAll = 1;</code>
     * @return The motorSpinAll.
     */
    boolean getMotorSpinAll();

    /**
     * <code>bool motorSpinSeq = 2;</code>
     * @return The motorSpinSeq.
     */
    boolean getMotorSpinSeq();

    /**
     * <code>bool payloadActuate = 3;</code>
     * @return The payloadActuate.
     */
    boolean getPayloadActuate();
  }
  /**
   * Protobuf type {@code TestStatus}
   */
  public static final class TestStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:TestStatus)
      TestStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        TestStatus.class.getName());
    }
    // Use TestStatus.newBuilder() to construct.
    private TestStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TestStatus() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestStatusOuterClass.internal_static_TestStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestStatusOuterClass.internal_static_TestStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestStatusOuterClass.TestStatus.class, TestStatusOuterClass.TestStatus.Builder.class);
    }

    public static final int MOTORSPINALL_FIELD_NUMBER = 1;
    private boolean motorSpinAll_ = false;
    /**
     * <code>bool motorSpinAll = 1;</code>
     * @return The motorSpinAll.
     */
    @java.lang.Override
    public boolean getMotorSpinAll() {
      return motorSpinAll_;
    }

    public static final int MOTORSPINSEQ_FIELD_NUMBER = 2;
    private boolean motorSpinSeq_ = false;
    /**
     * <code>bool motorSpinSeq = 2;</code>
     * @return The motorSpinSeq.
     */
    @java.lang.Override
    public boolean getMotorSpinSeq() {
      return motorSpinSeq_;
    }

    public static final int PAYLOADACTUATE_FIELD_NUMBER = 3;
    private boolean payloadActuate_ = false;
    /**
     * <code>bool payloadActuate = 3;</code>
     * @return The payloadActuate.
     */
    @java.lang.Override
    public boolean getPayloadActuate() {
      return payloadActuate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (motorSpinAll_ != false) {
        output.writeBool(1, motorSpinAll_);
      }
      if (motorSpinSeq_ != false) {
        output.writeBool(2, motorSpinSeq_);
      }
      if (payloadActuate_ != false) {
        output.writeBool(3, payloadActuate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (motorSpinAll_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, motorSpinAll_);
      }
      if (motorSpinSeq_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, motorSpinSeq_);
      }
      if (payloadActuate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, payloadActuate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TestStatusOuterClass.TestStatus)) {
        return super.equals(obj);
      }
      TestStatusOuterClass.TestStatus other = (TestStatusOuterClass.TestStatus) obj;

      if (getMotorSpinAll()
          != other.getMotorSpinAll()) return false;
      if (getMotorSpinSeq()
          != other.getMotorSpinSeq()) return false;
      if (getPayloadActuate()
          != other.getPayloadActuate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOTORSPINALL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMotorSpinAll());
      hash = (37 * hash) + MOTORSPINSEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMotorSpinSeq());
      hash = (37 * hash) + PAYLOADACTUATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPayloadActuate());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TestStatusOuterClass.TestStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static TestStatusOuterClass.TestStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static TestStatusOuterClass.TestStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static TestStatusOuterClass.TestStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TestStatusOuterClass.TestStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestStatus)
        TestStatusOuterClass.TestStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestStatusOuterClass.internal_static_TestStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestStatusOuterClass.internal_static_TestStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestStatusOuterClass.TestStatus.class, TestStatusOuterClass.TestStatus.Builder.class);
      }

      // Construct using TestStatusOuterClass.TestStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        motorSpinAll_ = false;
        motorSpinSeq_ = false;
        payloadActuate_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestStatusOuterClass.internal_static_TestStatus_descriptor;
      }

      @java.lang.Override
      public TestStatusOuterClass.TestStatus getDefaultInstanceForType() {
        return TestStatusOuterClass.TestStatus.getDefaultInstance();
      }

      @java.lang.Override
      public TestStatusOuterClass.TestStatus build() {
        TestStatusOuterClass.TestStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TestStatusOuterClass.TestStatus buildPartial() {
        TestStatusOuterClass.TestStatus result = new TestStatusOuterClass.TestStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TestStatusOuterClass.TestStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.motorSpinAll_ = motorSpinAll_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.motorSpinSeq_ = motorSpinSeq_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payloadActuate_ = payloadActuate_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestStatusOuterClass.TestStatus) {
          return mergeFrom((TestStatusOuterClass.TestStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestStatusOuterClass.TestStatus other) {
        if (other == TestStatusOuterClass.TestStatus.getDefaultInstance()) return this;
        if (other.getMotorSpinAll() != false) {
          setMotorSpinAll(other.getMotorSpinAll());
        }
        if (other.getMotorSpinSeq() != false) {
          setMotorSpinSeq(other.getMotorSpinSeq());
        }
        if (other.getPayloadActuate() != false) {
          setPayloadActuate(other.getPayloadActuate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                motorSpinAll_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                motorSpinSeq_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                payloadActuate_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean motorSpinAll_ ;
      /**
       * <code>bool motorSpinAll = 1;</code>
       * @return The motorSpinAll.
       */
      @java.lang.Override
      public boolean getMotorSpinAll() {
        return motorSpinAll_;
      }
      /**
       * <code>bool motorSpinAll = 1;</code>
       * @param value The motorSpinAll to set.
       * @return This builder for chaining.
       */
      public Builder setMotorSpinAll(boolean value) {

        motorSpinAll_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool motorSpinAll = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotorSpinAll() {
        bitField0_ = (bitField0_ & ~0x00000001);
        motorSpinAll_ = false;
        onChanged();
        return this;
      }

      private boolean motorSpinSeq_ ;
      /**
       * <code>bool motorSpinSeq = 2;</code>
       * @return The motorSpinSeq.
       */
      @java.lang.Override
      public boolean getMotorSpinSeq() {
        return motorSpinSeq_;
      }
      /**
       * <code>bool motorSpinSeq = 2;</code>
       * @param value The motorSpinSeq to set.
       * @return This builder for chaining.
       */
      public Builder setMotorSpinSeq(boolean value) {

        motorSpinSeq_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool motorSpinSeq = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotorSpinSeq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        motorSpinSeq_ = false;
        onChanged();
        return this;
      }

      private boolean payloadActuate_ ;
      /**
       * <code>bool payloadActuate = 3;</code>
       * @return The payloadActuate.
       */
      @java.lang.Override
      public boolean getPayloadActuate() {
        return payloadActuate_;
      }
      /**
       * <code>bool payloadActuate = 3;</code>
       * @param value The payloadActuate to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadActuate(boolean value) {

        payloadActuate_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool payloadActuate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayloadActuate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payloadActuate_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TestStatus)
    }

    // @@protoc_insertion_point(class_scope:TestStatus)
    private static final TestStatusOuterClass.TestStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TestStatusOuterClass.TestStatus();
    }

    public static TestStatusOuterClass.TestStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestStatus>
        PARSER = new com.google.protobuf.AbstractParser<TestStatus>() {
      @java.lang.Override
      public TestStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TestStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TestStatusOuterClass.TestStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TestStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TestStatus.proto\"P\n\nTestStatus\022\024\n\014moto" +
      "rSpinAll\030\001 \001(\010\022\024\n\014motorSpinSeq\030\002 \001(\010\022\026\n\016" +
      "payloadActuate\030\003 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TestStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_TestStatus_descriptor,
        new java.lang.String[] { "MotorSpinAll", "MotorSpinSeq", "PayloadActuate", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
