// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HealthStatus.proto
// Protobuf Java Version: 4.29.3

public final class HealthStatusOuterClass {
  private HealthStatusOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      HealthStatusOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HealthStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HealthStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool gps = 1;</code>
     * @return The gps.
     */
    boolean getGps();

    /**
     * <code>bool bat = 2;</code>
     * @return The bat.
     */
    boolean getBat();

    /**
     * <code>bool mtr = 3;</code>
     * @return The mtr.
     */
    boolean getMtr();

    /**
     * <code>bool imu = 4;</code>
     * @return The imu.
     */
    boolean getImu();

    /**
     * <code>bool log = 5;</code>
     * @return The log.
     */
    boolean getLog();

    /**
     * <code>bool cam = 6;</code>
     * @return The cam.
     */
    boolean getCam();

    /**
     * <code>bool str = 7;</code>
     * @return The str.
     */
    boolean getStr();

    /**
     * <code>bool rdo = 8;</code>
     * @return The rdo.
     */
    boolean getRdo();

    /**
     * <code>bool phk = 9;</code>
     * @return The phk.
     */
    boolean getPhk();
  }
  /**
   * Protobuf type {@code HealthStatus}
   */
  public static final class HealthStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HealthStatus)
      HealthStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        HealthStatus.class.getName());
    }
    // Use HealthStatus.newBuilder() to construct.
    private HealthStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HealthStatus() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HealthStatusOuterClass.internal_static_HealthStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HealthStatusOuterClass.internal_static_HealthStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HealthStatusOuterClass.HealthStatus.class, HealthStatusOuterClass.HealthStatus.Builder.class);
    }

    public static final int GPS_FIELD_NUMBER = 1;
    private boolean gps_ = false;
    /**
     * <code>bool gps = 1;</code>
     * @return The gps.
     */
    @java.lang.Override
    public boolean getGps() {
      return gps_;
    }

    public static final int BAT_FIELD_NUMBER = 2;
    private boolean bat_ = false;
    /**
     * <code>bool bat = 2;</code>
     * @return The bat.
     */
    @java.lang.Override
    public boolean getBat() {
      return bat_;
    }

    public static final int MTR_FIELD_NUMBER = 3;
    private boolean mtr_ = false;
    /**
     * <code>bool mtr = 3;</code>
     * @return The mtr.
     */
    @java.lang.Override
    public boolean getMtr() {
      return mtr_;
    }

    public static final int IMU_FIELD_NUMBER = 4;
    private boolean imu_ = false;
    /**
     * <code>bool imu = 4;</code>
     * @return The imu.
     */
    @java.lang.Override
    public boolean getImu() {
      return imu_;
    }

    public static final int LOG_FIELD_NUMBER = 5;
    private boolean log_ = false;
    /**
     * <code>bool log = 5;</code>
     * @return The log.
     */
    @java.lang.Override
    public boolean getLog() {
      return log_;
    }

    public static final int CAM_FIELD_NUMBER = 6;
    private boolean cam_ = false;
    /**
     * <code>bool cam = 6;</code>
     * @return The cam.
     */
    @java.lang.Override
    public boolean getCam() {
      return cam_;
    }

    public static final int STR_FIELD_NUMBER = 7;
    private boolean str_ = false;
    /**
     * <code>bool str = 7;</code>
     * @return The str.
     */
    @java.lang.Override
    public boolean getStr() {
      return str_;
    }

    public static final int RDO_FIELD_NUMBER = 8;
    private boolean rdo_ = false;
    /**
     * <code>bool rdo = 8;</code>
     * @return The rdo.
     */
    @java.lang.Override
    public boolean getRdo() {
      return rdo_;
    }

    public static final int PHK_FIELD_NUMBER = 9;
    private boolean phk_ = false;
    /**
     * <code>bool phk = 9;</code>
     * @return The phk.
     */
    @java.lang.Override
    public boolean getPhk() {
      return phk_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gps_ != false) {
        output.writeBool(1, gps_);
      }
      if (bat_ != false) {
        output.writeBool(2, bat_);
      }
      if (mtr_ != false) {
        output.writeBool(3, mtr_);
      }
      if (imu_ != false) {
        output.writeBool(4, imu_);
      }
      if (log_ != false) {
        output.writeBool(5, log_);
      }
      if (cam_ != false) {
        output.writeBool(6, cam_);
      }
      if (str_ != false) {
        output.writeBool(7, str_);
      }
      if (rdo_ != false) {
        output.writeBool(8, rdo_);
      }
      if (phk_ != false) {
        output.writeBool(9, phk_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gps_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, gps_);
      }
      if (bat_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, bat_);
      }
      if (mtr_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, mtr_);
      }
      if (imu_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, imu_);
      }
      if (log_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, log_);
      }
      if (cam_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, cam_);
      }
      if (str_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, str_);
      }
      if (rdo_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, rdo_);
      }
      if (phk_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, phk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HealthStatusOuterClass.HealthStatus)) {
        return super.equals(obj);
      }
      HealthStatusOuterClass.HealthStatus other = (HealthStatusOuterClass.HealthStatus) obj;

      if (getGps()
          != other.getGps()) return false;
      if (getBat()
          != other.getBat()) return false;
      if (getMtr()
          != other.getMtr()) return false;
      if (getImu()
          != other.getImu()) return false;
      if (getLog()
          != other.getLog()) return false;
      if (getCam()
          != other.getCam()) return false;
      if (getStr()
          != other.getStr()) return false;
      if (getRdo()
          != other.getRdo()) return false;
      if (getPhk()
          != other.getPhk()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GPS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGps());
      hash = (37 * hash) + BAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBat());
      hash = (37 * hash) + MTR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMtr());
      hash = (37 * hash) + IMU_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getImu());
      hash = (37 * hash) + LOG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLog());
      hash = (37 * hash) + CAM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCam());
      hash = (37 * hash) + STR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStr());
      hash = (37 * hash) + RDO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRdo());
      hash = (37 * hash) + PHK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPhk());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HealthStatusOuterClass.HealthStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static HealthStatusOuterClass.HealthStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static HealthStatusOuterClass.HealthStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static HealthStatusOuterClass.HealthStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HealthStatusOuterClass.HealthStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HealthStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HealthStatus)
        HealthStatusOuterClass.HealthStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HealthStatusOuterClass.internal_static_HealthStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HealthStatusOuterClass.internal_static_HealthStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HealthStatusOuterClass.HealthStatus.class, HealthStatusOuterClass.HealthStatus.Builder.class);
      }

      // Construct using HealthStatusOuterClass.HealthStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        gps_ = false;
        bat_ = false;
        mtr_ = false;
        imu_ = false;
        log_ = false;
        cam_ = false;
        str_ = false;
        rdo_ = false;
        phk_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HealthStatusOuterClass.internal_static_HealthStatus_descriptor;
      }

      @java.lang.Override
      public HealthStatusOuterClass.HealthStatus getDefaultInstanceForType() {
        return HealthStatusOuterClass.HealthStatus.getDefaultInstance();
      }

      @java.lang.Override
      public HealthStatusOuterClass.HealthStatus build() {
        HealthStatusOuterClass.HealthStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public HealthStatusOuterClass.HealthStatus buildPartial() {
        HealthStatusOuterClass.HealthStatus result = new HealthStatusOuterClass.HealthStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(HealthStatusOuterClass.HealthStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.gps_ = gps_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bat_ = bat_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mtr_ = mtr_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.imu_ = imu_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.log_ = log_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.cam_ = cam_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.str_ = str_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.rdo_ = rdo_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.phk_ = phk_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HealthStatusOuterClass.HealthStatus) {
          return mergeFrom((HealthStatusOuterClass.HealthStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HealthStatusOuterClass.HealthStatus other) {
        if (other == HealthStatusOuterClass.HealthStatus.getDefaultInstance()) return this;
        if (other.getGps() != false) {
          setGps(other.getGps());
        }
        if (other.getBat() != false) {
          setBat(other.getBat());
        }
        if (other.getMtr() != false) {
          setMtr(other.getMtr());
        }
        if (other.getImu() != false) {
          setImu(other.getImu());
        }
        if (other.getLog() != false) {
          setLog(other.getLog());
        }
        if (other.getCam() != false) {
          setCam(other.getCam());
        }
        if (other.getStr() != false) {
          setStr(other.getStr());
        }
        if (other.getRdo() != false) {
          setRdo(other.getRdo());
        }
        if (other.getPhk() != false) {
          setPhk(other.getPhk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                gps_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                bat_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                mtr_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                imu_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                log_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                cam_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                str_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                rdo_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                phk_ = input.readBool();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean gps_ ;
      /**
       * <code>bool gps = 1;</code>
       * @return The gps.
       */
      @java.lang.Override
      public boolean getGps() {
        return gps_;
      }
      /**
       * <code>bool gps = 1;</code>
       * @param value The gps to set.
       * @return This builder for chaining.
       */
      public Builder setGps(boolean value) {

        gps_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool gps = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGps() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gps_ = false;
        onChanged();
        return this;
      }

      private boolean bat_ ;
      /**
       * <code>bool bat = 2;</code>
       * @return The bat.
       */
      @java.lang.Override
      public boolean getBat() {
        return bat_;
      }
      /**
       * <code>bool bat = 2;</code>
       * @param value The bat to set.
       * @return This builder for chaining.
       */
      public Builder setBat(boolean value) {

        bat_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool bat = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bat_ = false;
        onChanged();
        return this;
      }

      private boolean mtr_ ;
      /**
       * <code>bool mtr = 3;</code>
       * @return The mtr.
       */
      @java.lang.Override
      public boolean getMtr() {
        return mtr_;
      }
      /**
       * <code>bool mtr = 3;</code>
       * @param value The mtr to set.
       * @return This builder for chaining.
       */
      public Builder setMtr(boolean value) {

        mtr_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool mtr = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMtr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mtr_ = false;
        onChanged();
        return this;
      }

      private boolean imu_ ;
      /**
       * <code>bool imu = 4;</code>
       * @return The imu.
       */
      @java.lang.Override
      public boolean getImu() {
        return imu_;
      }
      /**
       * <code>bool imu = 4;</code>
       * @param value The imu to set.
       * @return This builder for chaining.
       */
      public Builder setImu(boolean value) {

        imu_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool imu = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearImu() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imu_ = false;
        onChanged();
        return this;
      }

      private boolean log_ ;
      /**
       * <code>bool log = 5;</code>
       * @return The log.
       */
      @java.lang.Override
      public boolean getLog() {
        return log_;
      }
      /**
       * <code>bool log = 5;</code>
       * @param value The log to set.
       * @return This builder for chaining.
       */
      public Builder setLog(boolean value) {

        log_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool log = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLog() {
        bitField0_ = (bitField0_ & ~0x00000010);
        log_ = false;
        onChanged();
        return this;
      }

      private boolean cam_ ;
      /**
       * <code>bool cam = 6;</code>
       * @return The cam.
       */
      @java.lang.Override
      public boolean getCam() {
        return cam_;
      }
      /**
       * <code>bool cam = 6;</code>
       * @param value The cam to set.
       * @return This builder for chaining.
       */
      public Builder setCam(boolean value) {

        cam_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>bool cam = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCam() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cam_ = false;
        onChanged();
        return this;
      }

      private boolean str_ ;
      /**
       * <code>bool str = 7;</code>
       * @return The str.
       */
      @java.lang.Override
      public boolean getStr() {
        return str_;
      }
      /**
       * <code>bool str = 7;</code>
       * @param value The str to set.
       * @return This builder for chaining.
       */
      public Builder setStr(boolean value) {

        str_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool str = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000040);
        str_ = false;
        onChanged();
        return this;
      }

      private boolean rdo_ ;
      /**
       * <code>bool rdo = 8;</code>
       * @return The rdo.
       */
      @java.lang.Override
      public boolean getRdo() {
        return rdo_;
      }
      /**
       * <code>bool rdo = 8;</code>
       * @param value The rdo to set.
       * @return This builder for chaining.
       */
      public Builder setRdo(boolean value) {

        rdo_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool rdo = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRdo() {
        bitField0_ = (bitField0_ & ~0x00000080);
        rdo_ = false;
        onChanged();
        return this;
      }

      private boolean phk_ ;
      /**
       * <code>bool phk = 9;</code>
       * @return The phk.
       */
      @java.lang.Override
      public boolean getPhk() {
        return phk_;
      }
      /**
       * <code>bool phk = 9;</code>
       * @param value The phk to set.
       * @return This builder for chaining.
       */
      public Builder setPhk(boolean value) {

        phk_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>bool phk = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhk() {
        bitField0_ = (bitField0_ & ~0x00000100);
        phk_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HealthStatus)
    }

    // @@protoc_insertion_point(class_scope:HealthStatus)
    private static final HealthStatusOuterClass.HealthStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HealthStatusOuterClass.HealthStatus();
    }

    public static HealthStatusOuterClass.HealthStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthStatus>
        PARSER = new com.google.protobuf.AbstractParser<HealthStatus>() {
      @java.lang.Override
      public HealthStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HealthStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public HealthStatusOuterClass.HealthStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HealthStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HealthStatus.proto\"\203\001\n\014HealthStatus\022\013\n" +
      "\003gps\030\001 \001(\010\022\013\n\003bat\030\002 \001(\010\022\013\n\003mtr\030\003 \001(\010\022\013\n\003" +
      "imu\030\004 \001(\010\022\013\n\003log\030\005 \001(\010\022\013\n\003cam\030\006 \001(\010\022\013\n\003s" +
      "tr\030\007 \001(\010\022\013\n\003rdo\030\010 \001(\010\022\013\n\003phk\030\t \001(\010b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HealthStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HealthStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HealthStatus_descriptor,
        new java.lang.String[] { "Gps", "Bat", "Mtr", "Imu", "Log", "Cam", "Str", "Rdo", "Phk", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
